/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  sports_announcements: () => import("@/views/sports/announcements/index.vue"),
  sports_awards: () => import("@/views/sports/awards/index.vue"),
  sports_departments: () => import("@/views/sports/departments/index.vue"),
  sports_events: () => import("@/views/sports/events/index.vue"),
  sports_items: () => import("@/views/sports/items/index.vue"),
  sports_registrations: () => import("@/views/sports/registrations/index.vue"),
  sports_results: () => import("@/views/sports/results/index.vue"),
  sports_schedules: () => import("@/views/sports/schedules/index.vue"),
  sports_users: () => import("@/views/sports/users/index.vue"),
};
