/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '仪表盘',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'sports',
    path: '/sports',
    component: 'layout.base',
    meta: {
      title: '运动会管理',
      icon: 'mdi:trophy-outline',
      order: 2,
      roles: ['ROLE_ADMIN'],
      i18nKey: 'route.sports'
    },
    children: [
      {
        name: 'sports_announcements',
        path: '/sports/announcements',
        component: 'view.sports_announcements',
        meta: {
          title: '公告管理',
          icon: 'mdi:bullhorn-outline',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_announcements'
        }
      },
      {
        name: 'sports_awards',
        path: '/sports/awards',
        component: 'view.sports_awards',
        meta: {
          title: '奖项管理',
          icon: 'mdi:medal',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_awards'
        }
      },
      {
        name: 'sports_departments',
        path: '/sports/departments',
        component: 'view.sports_departments',
        meta: {
          title: '院系管理',
          icon: 'mdi:office-building',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_departments'
        }
      },
      {
        name: 'sports_events',
        path: '/sports/events',
        component: 'view.sports_events',
        meta: {
          title: '赛事管理',
          icon: 'mdi:calendar-star',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_events'
        }
      },
      {
        name: 'sports_items',
        path: '/sports/items',
        component: 'view.sports_items',
        meta: {
          title: '项目管理',
          icon: 'mdi:run-fast',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_items'
        }
      },
      {
        name: 'sports_registrations',
        path: '/sports/registrations',
        component: 'view.sports_registrations',
        meta: {
          title: '报名管理',
          icon: 'mdi:clipboard-list-outline',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_registrations'
        }
      },
      {
        name: 'sports_results',
        path: '/sports/results',
        component: 'view.sports_results',
        meta: {
          title: '成绩管理',
          icon: 'mdi:chart-line',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_results'
        }
      },
      {
        name: 'sports_schedules',
        path: '/sports/schedules',
        component: 'view.sports_schedules',
        meta: {
          title: '赛程管理',
          icon: 'mdi:calendar-clock',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_schedules'
        }
      },
      {
        name: 'sports_users',
        path: '/sports/users',
        component: 'view.sports_users',
        meta: {
          title: '用户管理',
          icon: 'mdi:account-multiple',
          roles: ['ROLE_ADMIN'],
          i18nKey: 'route.sports_users'
        }
      }
    ]
  }
];
